server:
  port: 9080
  context-path: /nfcm
  #ssl:
  #  key-store: classpath:keystore.p12
  #  key-store-password: '123456'
  #  keyAlias: tomcat
  #  keyStoreType: PKCS12
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xdlcm?useSSL=false&characterEncoding=utf-8
    username: xdlcm
    password: xdlcm
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/home/admin/fileSavePath/
   
logging:
  level:
    com.nantian.nfcm: debug
debug: true 

